### ISSUE TITLE
Address->asWallet for testnet

### ISSUE THREAD

**Issue by kolirt** [olifanton/interop#6]
```php
$hex = '0:cee60beac1b291cf24b441ed37df04464ac84b36ee60720433dc5a202a99514d';

$address = new Address($address);
$address->asWallet();
$address->asContract();
```

https://github.com/olifanton/interop/blob/31064d373952921cfe31bd03d5e4c1d448d56a8f/src/Olifanton/Interop/Address.php#L89

I think it's worth making a method that will switch the address to the test network

**Comment by romanzaycev** [comment]
Added in [1.4.3](https://github.com/olifanton/interop/releases/tag/1.4.3)
